"""Rule implementations for the pre-review rules engine.

Each rule is a pure function ``(RuleContext) -> list[RuleFinding]``.
Functions must not raise on missing files, malformed YAML, or unparseable
Python — they should return an empty list or a targeted finding.

Rules are kept in one module on purpose: the whole set is < 500 lines,
and collocating them makes it easy to keep naming / categories / severity
consistent.
"""

from __future__ import annotations

import ast
import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .engine import RuleFinding
else:
    from .engine import RuleFinding  # runtime import for building findings


# -----------------------------------------------------------------------------
# R-scaffold-only
# -----------------------------------------------------------------------------

# Filenames that count as "structural fluff" — if the diff consists almost
# entirely of these, the worker has not actually implemented the feature.
#
# Go-generated artefacts (.pb.go, _grpc.pb.go, _mock.go, go.sum) are listed
# alongside the Python / TS fluff because protobuf-generated code and
# mock files are produced by tooling, not by the developer; a diff that
# adds only those is a scaffold, identical to "added an empty __init__.py".
_STRUCTURAL_FLUFF_SUFFIXES = (
    "/__init__.py",
    ".generated.ts",
    ".generated.tsx",
    ".generated.js",
    "openapi.json",
    "package-lock.json",
    ".snap",
    ".pb.go",
    "_grpc.pb.go",
    "_mock.go",
    "_gen.go",
    "go.sum",
)
_MIN_IMPLEMENTATION_BYTES = 200


def rule_scaffold_only(ctx) -> list:
    """Block diffs that contain only empty __init__.py + regenerated artefacts.

    Heuristic: count "substantive" files vs "structural fluff" in
    files_changed. A file is substantive if (a) its name does not end in
    a fluff suffix, AND (b) either it does not exist on disk (true delete
    / rename pathology) or it has >= ``_MIN_IMPLEMENTATION_BYTES`` bytes
    of content.

    Rationale: BI-001e committed `backend/scripts/__init__.py` (0 bytes)
    and `frontend/src/api/types.generated.ts` (regenerated by tooling).
    The goal listed five files that had to exist; none of them appeared
    in the diff. Verify commands would have failed on the first
    ``test -f`` — but the LLM reviewer gave a thoughtful design critique
    anyway. This rule catches that class in <10 ms.
    """
    substantive = 0
    fluff: list[str] = []
    for rel in ctx.files_changed:
        is_fluff = rel.endswith(_STRUCTURAL_FLUFF_SUFFIXES)
        if is_fluff:
            # Pure structural fluff is never substantive.
            fluff.append(rel)
            continue
        contents = ctx.read_text_safe(rel)
        if contents is None:
            # File no longer readable (renamed / deleted). Count as
            # substantive — it's a real change even without byte count.
            substantive += 1
            continue
        if len(contents.encode("utf-8", errors="replace")) >= _MIN_IMPLEMENTATION_BYTES:
            substantive += 1
        else:
            # Below the threshold: treat as fluff, but record specifically
            # so the report can name the offending file.
            fluff.append(rel)

    if substantive == 0 and fluff:
        return [
            RuleFinding(
                rule_id="R-scaffold-only",
                severity="blocker",
                file=fluff[0],
                line=None,
                category="correctness",
                summary=(
                    f"Diff contains only {len(fluff)} structural/fluff file(s); "
                    "no substantive implementation"
                ),
                why=(
                    "The diff adds only empty __init__.py modules, regenerated "
                    "TS types, OpenAPI JSON, or similar placeholders. If the "
                    "feature goal names real files, none of them were "
                    "implemented. Likely cause: the worker stopped after the "
                    "scaffold step. Sending this to the senior review squad "
                    "wastes ~$5 of LLM budget before any merge can land."
                ),
                fix=(
                    "Re-run the worker with an AGENT_BRIEF that spells out "
                    "each file path required by the goal and asks for a "
                    "complete implementation, not just stubs. If the goal is "
                    "genuinely a scaffold-only ticket, tag the feature with "
                    "`scaffold_only: true` in features.json so this rule "
                    "allows it."
                ),
            )
        ]
    return []


# -----------------------------------------------------------------------------
# R-goal-file-missing
# -----------------------------------------------------------------------------

# Extract path-shaped tokens from the feature goal. We look for tokens
# that start with a recognised top-level directory and end in a known
# source-file extension. Narrow on purpose to avoid false positives from
# prose like "users/456/orders".
_GOAL_PATH_RE = re.compile(
    r"\b((?:backend|frontend|src|migrations|config|tests|scripts|prompts|"
    r"docs|namespaces)/"
    r"[A-Za-z0-9_./\-]+?"
    r"\.(?:py|ts|tsx|js|jsx|sql|yaml|yml|json|md|toml|css|html))\b"
)


def rule_goal_file_missing(ctx) -> list:
    """Block when the goal names files that the diff does not include.

    Example from BI-001d / BI-001e: goal said
    "Commit `backend/app/api/auth/magic.py`" but the diff did not add
    that path. The LLM reviewer called this out as a blocker on the
    third retry; this rule catches it on the zeroth.

    False-positive guard: we only flag paths that appear INSIDE a code
    fence or with a verb indicating creation. Prose like "inspired by
    backend/app/main.py" is not a creation directive.
    """
    goal = ctx.feature_goal or ""
    # Extract candidate paths.
    candidates = set(_GOAL_PATH_RE.findall(goal))
    if not candidates:
        return []

    # Keep only paths that appear in a creation context. We accept either
    # (a) inside a code fence / indented block, OR (b) after a verb of
    # creation within the same sentence.
    creation_verbs = re.compile(
        r"\b(create|add|commit|implement|write|generate|include|ensure|"
        r"produce|deliver|supply|файл|создай|добавь|напиши)\b",
        re.IGNORECASE,
    )
    keep: set[str] = set()
    for candidate in candidates:
        # Look at the 120 chars before each occurrence; if a creation
        # verb is present there OR the path sits inside backticks, keep.
        for m in re.finditer(re.escape(candidate), goal):
            window = goal[max(0, m.start() - 120) : m.start()]
            if creation_verbs.search(window):
                keep.add(candidate)
                break
            # Backticked path — in this codebase's goals that always
            # means "this file must exist".
            if goal[max(0, m.start() - 1) : m.start()] == "`":
                keep.add(candidate)
                break

    changed = set(ctx.files_changed)
    missing = sorted(keep - changed)
    if not missing:
        return []

    # Cap how many we surface in a single finding; N>5 usually means the
    # rule is misreading a complex prose goal and a single blocker is
    # enough to force a human look.
    display = missing[:5]
    more = f" (+{len(missing) - 5} more)" if len(missing) > 5 else ""
    return [
        RuleFinding(
            rule_id="R-goal-file-missing",
            severity="blocker",
            file=display[0],
            line=None,
            category="correctness",
            summary=(
                f"Goal requires {len(missing)} file(s) not in the diff: {', '.join(display)}{more}"
            ),
            why=(
                "The feature goal names specific file paths as deliverables, "
                "but the diff does not add them. Either the worker stopped "
                "early, or the goal text disagrees with what was actually "
                "built. Senior review cannot evaluate a module that does not "
                "exist; pointing this out costs ~$1/reviewer."
            ),
            fix=(
                "Either (a) re-run the worker asking specifically for the "
                "missing file(s), or (b) if the goal prose is wrong, correct "
                "the goal in features.json before the next attempt so the "
                "spec and the implementation agree."
            ),
        )
    ]


# -----------------------------------------------------------------------------
# R-silent-except
# -----------------------------------------------------------------------------


# Match attribute calls like ``logger.warning(...)`` or ``log.error(...)``
# used to check whether an exception handler actually logs. Metric
# increments are also accepted (any call whose callee name contains
# "metric" or "counter" in its dotted path).
def _handler_has_observability(handler: ast.ExceptHandler) -> bool:
    for node in ast.walk(handler):
        if isinstance(node, ast.Call):
            name = _dotted_name(node.func).lower()
            if not name:
                continue
            if any(
                tok in name
                for tok in (
                    "log.",
                    "logger.",
                    "logging.",
                    "metric",
                    "counter",
                    "histogram",
                    "observe",
                    "sentry",
                    "capture",
                )
            ):
                return True
        if isinstance(node, ast.Raise):
            return True  # re-raise is fine — not silent
    return False


def _dotted_name(node: ast.AST) -> str:
    """Best-effort dotted name for an AST node (``a.b.c``)."""
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        base = _dotted_name(node.value)
        return f"{base}.{node.attr}" if base else node.attr
    return ""


def _exception_handler_is_bare(handler: ast.ExceptHandler) -> bool:
    """True when the handler catches ``Exception`` / ``BaseException`` / nothing."""
    if handler.type is None:
        return True
    name = _dotted_name(handler.type)
    return name in ("Exception", "BaseException", "builtins.Exception", "builtins.BaseException")


def rule_silent_except(ctx) -> list:
    """Block ``except Exception: <silent return / pass>`` in project code.

    Seen in BI-006 (`semantic.py:360`): `except Exception: return frozenset()`
    with no log, no counter, no health signal. On CH outage the forbidden
    terms gate silently stopped enforcing everything except the hard-coded
    floor.

    We inspect every .py file added or modified in the diff. A handler is
    a violation when BOTH:
      1. It catches Exception / BaseException / bare `except:`.
      2. Its body contains no log/metric/raise call.

    Files under ``tests/`` and ``tests_v2/`` are skipped — silencing an
    exception is sometimes the whole point of a test.
    """
    findings: list = []
    for rel in ctx.files_changed:
        if not rel.endswith(".py"):
            continue
        # Skip tests — explicit `pytest.raises(Exception)` and similar
        # patterns routinely look like silent handlers but are correct.
        parts = rel.split("/")
        if "tests" in parts or "tests_v2" in parts:
            continue
        src = ctx.read_text_safe(rel)
        if not src:
            continue
        try:
            tree = ast.parse(src, filename=rel)
        except SyntaxError:
            continue

        for node in ast.walk(tree):
            if not isinstance(node, ast.Try):
                continue
            for handler in node.handlers:
                if not _exception_handler_is_bare(handler):
                    continue
                if _handler_has_observability(handler):
                    continue
                # Require the body to be non-trivial silence — pure
                # `pass` or a single `return` statement. A handler that
                # does actual work (e.g. cleanup) without logging is
                # handled by project code review, not this rule.
                body = handler.body
                is_silent = len(body) == 1 and isinstance(
                    body[0], (ast.Pass, ast.Return, ast.Continue)
                )
                if not is_silent:
                    continue
                # Comment-suppression escape hatch — lets a module opt
                # out with "# rules-ignore: silent-except" on the handler
                # line. (The marker avoids the `noqa:` prefix so that ruff
                # does not flag it as an unknown noqa code.)
                suppress_line = (
                    src.splitlines()[handler.lineno - 1]
                    if handler.lineno <= len(src.splitlines())
                    else ""
                )
                if "rules-ignore: silent-except" in suppress_line:
                    continue
                findings.append(
                    RuleFinding(
                        rule_id="R-silent-except",
                        severity="blocker",
                        file=rel,
                        line=handler.lineno,
                        category="observability",
                        summary="Silent `except Exception` swallows all errors",
                        why=(
                            "A bare `except Exception` returning a fallback "
                            "with no log, no counter, no health-check signal "
                            "turns every upstream failure into silent "
                            "degradation. If this code path touches CH, PG, "
                            "NATS, HTTP, or SSH, an outage will go unnoticed "
                            "until someone reads numbers by hand. Project "
                            "resilience rule R-2 treats this as a BLOCKER."
                        ),
                        fix=(
                            "Replace with `except <SpecificDriverError>:` and "
                            "inside the handler emit `log.warning(..., "
                            "exc_info=True)`, increment a counter (e.g. "
                            "`<module>_<op>_failures_total`), surface a "
                            "boolean `<op>_degraded` on /readyz, then "
                            "return the fallback. If the handler really is "
                            "correct as-is, add `# rules-ignore: silent-except` "
                            "on the handler line and a one-line justification."
                        ),
                    )
                )
    return findings


# -----------------------------------------------------------------------------
# R-sql-identifier-fstring
# -----------------------------------------------------------------------------

# Match a SQL keyword that introduces an identifier position, followed by
# an f-string placeholder or a string concatenation. Pragmatic regex;
# we accept some false positives (MAJOR, not BLOCKER) in exchange for
# simplicity. The project's SQL style guide is lowercase keywords; we
# match both cases anyway to be forgiving.
_SQL_KEYWORD = r"(?:FROM|JOIN|INTO|UPDATE|TABLE)"
_FSTRING_IDENT_RE = re.compile(
    rf"""f["'][^"']*\b{_SQL_KEYWORD}\s+\{{[^{{}}]+\}}""",
    re.IGNORECASE,
)
_CONCAT_IDENT_RE = re.compile(
    rf"""\b{_SQL_KEYWORD}\s+["']\s*\+\s*[A-Za-z_][A-Za-z0-9_]*""",
    re.IGNORECASE,
)


def rule_sql_identifier_fstring(ctx) -> list:
    """Block string-formatted table/column identifiers in SQL.

    Seen in BI-005: `f"SELECT ... FROM {table}"` guarded only by a
    whitelist + regex. Whitelists drift as new tables are added; regex
    misses Unicode homoglyphs. The only safe form is identifier quoting
    from the driver (psycopg.sql.Identifier, clickhouse-connect bound
    identifier).

    We grep the raw source of every .py file; AST-only analysis would
    miss identifiers built in helpers and passed down. The category is
    `security` and the severity is BLOCKER.
    """
    findings: list = []
    for rel in ctx.files_changed:
        if not rel.endswith(".py"):
            continue
        src = ctx.read_text_safe(rel)
        if not src:
            continue
        # Scan line-by-line so we can report a useful line number.
        for lineno, line in enumerate(src.splitlines(), start=1):
            if _FSTRING_IDENT_RE.search(line) or _CONCAT_IDENT_RE.search(line):
                findings.append(
                    RuleFinding(
                        rule_id="R-sql-identifier-fstring",
                        severity="blocker",
                        file=rel,
                        line=lineno,
                        category="security",
                        summary=("SQL identifier interpolated via f-string or concatenation"),
                        why=(
                            "Building a table / column / schema name into SQL "
                            "with f-string or `+` is a SQL-injection primitive. "
                            "Whitelists and regex guards drift as the schema "
                            "grows and miss Unicode homoglyphs; this class of "
                            "bug is one of the top causes of auth-bypass "
                            "incidents in production."
                        ),
                        fix=(
                            "Use the driver's identifier API: "
                            "`psycopg.sql.Identifier(name)` for PostgreSQL; "
                            "clickhouse-connect's parameter binding for CH. "
                            "If the relation really must be dynamic, validate "
                            "against `information_schema.tables` at call time "
                            "AND bind via the driver — never concatenate."
                        ),
                    )
                )
    return findings


# -----------------------------------------------------------------------------
# R-metrics-unit-mismatch
# -----------------------------------------------------------------------------

# Physical-quantity → expected units.
_QUANTITY_UNITS: dict[str, tuple[str, ...]] = {
    "масса": ("т", "кг", "г", "тонн"),
    "массы": ("т", "кг", "г", "тонн"),
    "объём": ("м³", "тыс м³", "тыс. м³", "л", "мл"),
    "объёма": ("м³", "тыс м³", "тыс. м³", "л", "мл"),
    "объем": ("м³", "тыс м³", "тыс. м³", "л", "мл"),
    "время": ("ч", "мин", "сек", "с"),
    "длительность": ("ч", "мин", "сек", "с"),
    "количество": ("шт", "ед", "раз"),
}


def rule_metrics_unit_mismatch(ctx) -> list:
    """Flag metrics.yaml entries where description and unit disagree.

    BI-006 example: `waste_rock_volume` with description
    "Суммарная масса вскрышных пород" and unit "м³". Either the number
    is mass (in which case the unit is wrong) or it is volume (the
    description). We cannot decide which; we flag both as BLOCKER and
    ask the author to choose.

    Scope: `config/metrics.yaml` at the namespace level. The rule
    activates only when that file is in the diff.
    """
    target = "config/metrics.yaml"
    if target not in ctx.files_changed:
        return []
    src = ctx.read_text_safe(target)
    if not src:
        return []

    import yaml

    try:
        data = yaml.safe_load(src) or {}
    except yaml.YAMLError:
        return []

    metrics = data.get("metrics", data)  # tolerate either top-level form
    if not isinstance(metrics, dict):
        return []

    findings: list = []
    for metric_id, entry in metrics.items():
        if not isinstance(entry, dict):
            continue
        description = str(entry.get("description", "")).lower()
        unit = str(entry.get("unit", ""))
        for quantity, units in _QUANTITY_UNITS.items():
            if quantity not in description:
                continue
            if unit and not any(u.lower() == unit.lower() for u in units):
                findings.append(
                    RuleFinding(
                        rule_id="R-metrics-unit-mismatch",
                        severity="blocker",
                        file=target,
                        line=None,
                        category="units",
                        summary=(
                            f"metric `{metric_id}`: description mentions "
                            f"{quantity!r} but unit is {unit!r}"
                        ),
                        why=(
                            "The description and unit disagree on the "
                            "physical quantity. An operator looking at the "
                            "widget sees two incompatible claims and has no "
                            "way to decide which is authoritative. Mining "
                            "convention in this project: добыча = т, "
                            "вскрыша / навал = тыс м³. Use the convention."
                        ),
                        fix=(
                            "Rewrite either the description (to match the "
                            "unit) or the unit + SQL (to match the quantity "
                            "actually computed). The SQL expression and the "
                            "description must agree too: sum(volume_m3) is "
                            "volume, not mass."
                        ),
                    )
                )
                break  # one finding per metric is enough
    return findings


# -----------------------------------------------------------------------------
# R-metrics-sanity-bounds-period
# -----------------------------------------------------------------------------

_PERIOD_BUCKETS_WIDE = {"week", "month", "quarter", "year"}


def rule_metrics_sanity_bounds_period(ctx) -> list:
    """Flag sanity_bounds that cannot survive weekly+ aggregation.

    If ``dimensions.period`` contains ``week|month|quarter`` but
    ``sanity_bounds.max`` is plausible only for a single shift (≤ 24),
    the first weekly aggregate will trip the bound. Severity MAJOR: the
    number may still render; this is calibration drift, not a correctness
    bug.
    """
    target = "config/metrics.yaml"
    if target not in ctx.files_changed:
        return []
    src = ctx.read_text_safe(target)
    if not src:
        return []

    import yaml

    try:
        data = yaml.safe_load(src) or {}
    except yaml.YAMLError:
        return []

    metrics = data.get("metrics", data)
    if not isinstance(metrics, dict):
        return []

    findings: list = []
    for metric_id, entry in metrics.items():
        if not isinstance(entry, dict):
            continue
        bounds = entry.get("sanity_bounds", {}) or {}
        if not isinstance(bounds, dict):
            continue
        bound_max = bounds.get("max")
        if not isinstance(bound_max, (int, float)):
            continue
        dims = entry.get("dimensions", []) or []
        # Accept either a list of dicts (structured) or list of strings
        # (lightweight config); we look for a `period` key with known
        # wide buckets.
        wide = False
        for d in dims:
            if isinstance(d, dict):
                for k, v in d.items():
                    if k in ("period", "period_buckets") and (
                        (
                            isinstance(v, (list, tuple))
                            and any(str(b).lower() in _PERIOD_BUCKETS_WIDE for b in v)
                        )
                        or (isinstance(v, str) and v.lower() in _PERIOD_BUCKETS_WIDE)
                    ):
                        wide = True
            elif isinstance(d, str) and d.lower() in _PERIOD_BUCKETS_WIDE:
                wide = True
        if wide and bound_max <= 24:
            findings.append(
                RuleFinding(
                    rule_id="R-metrics-sanity-bounds-period",
                    severity="major",
                    file=target,
                    line=None,
                    category="units",
                    summary=(
                        f"metric `{metric_id}`: sanity_bounds.max={bound_max} "
                        "too tight for weekly/monthly/quarterly aggregation"
                    ),
                    why=(
                        "The metric declares wide aggregation periods "
                        "(week / month / quarter), but the upper sanity "
                        "bound is plausible only for a single shift. The "
                        "first weekly aggregate will be flagged as an "
                        "outlier, and the operator will learn to ignore "
                        "the bounds — worse than having none."
                    ),
                    fix=(
                        "Either (a) split into period-scoped metrics "
                        "(`downtime_hours_shift`, `downtime_hours_month`) "
                        "with independent bounds, or (b) raise max to a "
                        "realistic ceiling for the longest period "
                        "(e.g. 24 * 90 * N_units for a quarter)."
                    ),
                )
            )
    return findings
